name: media-immersion
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.6.4
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.12.9
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.56.0
      - idna==3.10
      - kiwisolver==1.4.8
      - matplotlib==3.10.1
      - numpy==2.2.4
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.3
      - seaborn==0.13.2
      - six==1.17.0
      - tzdata==2025.2
      - urllib3==2.3.0
